/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_handhandlab_openssltest_OpensslTest */

#ifndef _Included_com_handhandlab_openssltest_OpensslTest
#define _Included_com_handhandlab_openssltest_OpensslTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_handhandlab_openssltest_OpensslTest
 * Method:    test
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_handhandlab_openssltest_OpensslTest_test
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_handhandlab_openssltest_OpensslTest
 * Method:    generateCA
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_handhandlab_openssltest_OpensslTest_generateCA
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_handhandlab_openssltest_OpensslTest
 * Method:    generateCert
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/handhandlab/agentdroid/openssl/CertWrapper;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_handhandlab_openssltest_OpensslTest_generateCert
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

/*
 * Class:     com_handhandlab_openssltest_OpensslTest
 * Method:    getKey
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_handhandlab_openssltest_OpensslTest_getKey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
